---

kind: pipeline
name: default
steps:

- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags

- name: audit
  image: node:14
  commands:
  - npm audit --package-lock-only --audit-level=moderate --production

- name: install
  image: node:14
  commands:
  - npm ci
  environment:
    NPM_CONFIG_IGNORE_SCRIPTS: true

- name: test
  image: node:14
  commands:
  - npm test

- name: build
  image: node:14
  commands:
    - npm run build
    - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

- name: static-security-scan
  image: quay.io/natlibfi/njsscan
  commands:
    - njsscan dist

- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-api
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: I1HjanmdJMXM7fmhYK8/hreMegej48Lxu49lQfMqhCqYh3CfnmZM0Mzk79E4A7deZ3k=
---
kind: secret
name: docker_password
data: t6JlYm9oVATVNrcLL8RiXUFYhc2tX9Vd0ysELZtw4FkYUsh8qBGczx2YrM869JHHZMm25uH8Tb4UlxQiU5bYBhgpFCuL/YvL5MPlah6OkETyyq1T42mmA8YrqFM=
---
kind: signature
hmac: 73ea062fb5834b72ffe55f03d6a31240ff1b602cb09f9ede09e0138aef1646b9

...
