language: node_js
node_js:
  - 'node'
  - '8'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
- npm install
before_script:
  - sleep 15
  - mongo melinda-record-import-api --eval 'db.createUser({user:"generalAdmin",pwd:"ToDoChangeAdmin",roles:["readWrite"]});'
scripts:
- npm test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - mongodb